### ISSUE TITLE
Add SQLLite to Backend to Store Attendance Report

### ISSUE THREAD

**Issue by suyash-singh101** [GeekGawd/Attendance-Face-Recognition-System#2]
The Attendance system needs SQLLite, we don't really need anything heavy. I think SQLAlchemy is more than enough and feel free to use GPT or any good ORMs for this. 

The Database modeling I will leave upto to you. The only requirement needed is that:

- IN-Time Logic: Whenever on a day a student shows the face for the first time, that is noted as the in_time, it won't updated. That is after initialisation it won't be updated.
- OUT-Time Logic: Whenever student shows his/her face just update the out-time field everytime.

**Comment by GeekGawd** [comment]
This has been added with the following commit, https://github.com/GeekGawd/Attendance-Face-Recognition-System/commit/b6624596d028cd10d090d02c943c82dc0ecdb58b a very crude implementation and a makeshift solution. Can face bugs and performance issues, feel free to upgrade to it to something better in the future or add better logic to it.

**Comment by suyash-singh101** [comment]
This has been added with the following commit, https://github.com/GeekGawd/Attendance-Face-Recognition-System/commit/b6624596d028cd10d090d02c943c82dc0ecdb58b a very crude implementation and a makeshift solution. Can face bugs and performance issues, feel free to upgrade to it to something better in the future or add better logic to it.
